> **提示**：欢迎参加“调查数据集”项目！引用段会添加这类提示，来帮助你制定调查方法。在你提交项目之前，你可以浏览一下报告，将这一段删除，以保持报告的简洁性。首先，你需要双击该 Markdown 框(cell)，将标题更改为与数据集和调查相关的标题。

# 项目：调查数据集（请用更具体的标题来代替这个标题！）

## 目录
<ul>
<li><a href="#intro">简介</a></li>
<li><a href="#wrangling">数据整理</a></li>
<li><a href="#eda">探索性数据分析</a></li>
<li><a href="#conclusions">结论</a></li>
</ul>

<a id='intro'></a>
## 简介

> **提示**：在报告的这一部分，你需要首先对已选择进行分析的数据集进行简要的介绍。在这一部分末尾，对你计划在报告过程中探索的问题进行描述。你需要建立至少包含一个因变量和三个自变量的分析报告。如果你不确定要问什么问题，请务必先熟悉数据集、数据集变量以及数据集上下文，以便确定要探索的问题。

> 如果尚未选择和下载数据，务必先进行这一步，再回到这里。如需在这个工作区中处理数据，还需要将其上传到工作区。因此，请单击左上角的 jupyter 图标，回到工作区目录。右上角有一个‘上传’按钮，可以将你的数据文件添加到工作区。然后单击 .ipynb 文件名，回到这里。

Notes for Football Data

All data is in csv format, ready for use within standard spreadsheet applications. Please note that some abbreviations are no longer in use (in particular odds from specific bookmakers no longer used) and refer to data collected in earlier seasons. For a current list of what bookmakers are included in the dataset please visit http://www.football-data.co.uk/matches.php

Key to results data:

    Div = League Division
    Date = Match Date (dd/mm/yy)
    HomeTeam = Home Team
    AwayTeam = Away Team
    FTHG and HG = Full Time Home Team Goals
    FTAG and AG = Full Time Away Team Goals
    FTR and Res = Full Time Result (H=Home Win, D=Draw, A=Away Win)
    HTHG = Half Time Home Team Goals
    HTAG = Half Time Away Team Goals
    HTR = Half Time Result (H=Home Win, D=Draw, A=Away Win)

    Match Statistics (where available)
    Attendance = Crowd Attendance
    Referee = Match Referee
    HS = Home Team Shots
    AS = Away Team Shots
    HST = Home Team Shots on Target
    AST = Away Team Shots on Target
    HHW = Home Team Hit Woodwork
    AHW = Away Team Hit Woodwork
    HC = Home Team Corners
    AC = Away Team Corners
    HF = Home Team Fouls Committed
    AF = Away Team Fouls Committed
    HFKC = Home Team Free Kicks Conceded
    AFKC = Away Team Free Kicks Conceded
    HO = Home Team Offsides
    AO = Away Team Offsides
    HY = Home Team Yellow Cards
    AY = Away Team Yellow Cards
    HR = Home Team Red Cards
    AR = Away Team Red Cards
    HBP = Home Team Bookings Points (10 = yellow, 25 = red)
    ABP = Away Team Bookings Points (10 = yellow, 25 = red)

Note that Free Kicks Conceeded includes fouls, offsides and any other offense commmitted and will always be equal to or higher than the number of fouls. Fouls make up the vast majority of Free Kicks Conceded. Free Kicks Conceded are shown when specific data on Fouls are not available (France 2nd, Belgium 1st and Greece 1st divisions).

Note also that English and Scottish yellow cards do not include the initial yellow card when a second is shown to a player converting it into a red, but this is included as a yellow (plus red) for European games.


Key to 1X2 (match) betting odds data:

    B365H = Bet365 home win odds
    B365D = Bet365 draw odds
    B365A = Bet365 away win odds
    BSH = Blue Square home win odds
    BSD = Blue Square draw odds
    BSA = Blue Square away win odds
    BWH = Bet&Win home win odds
    BWD = Bet&Win draw odds
    BWA = Bet&Win away win odds
    GBH = Gamebookers home win odds
    GBD = Gamebookers draw odds
    GBA = Gamebookers away win odds
    IWH = Interwetten home win odds
    IWD = Interwetten draw odds
    IWA = Interwetten away win odds
    LBH = Ladbrokes home win odds
    LBD = Ladbrokes draw odds
    LBA = Ladbrokes away win odds
    PSH and PH = Pinnacle home win odds
    PSD and PD = Pinnacle draw odds
    PSA and PA = Pinnacle away win odds
    SOH = Sporting Odds home win odds
    SOD = Sporting Odds draw odds
    SOA = Sporting Odds away win odds
    SBH = Sportingbet home win odds
    SBD = Sportingbet draw odds
    SBA = Sportingbet away win odds
    SJH = Stan James home win odds
    SJD = Stan James draw odds
    SJA = Stan James away win odds
    SYH = Stanleybet home win odds
    SYD = Stanleybet draw odds
    SYA = Stanleybet away win odds
    VCH = VC Bet home win odds
    VCD = VC Bet draw odds
    VCA = VC Bet away win odds
    WHH = William Hill home win odds
    WHD = William Hill draw odds
    WHA = William Hill away win odds

    Bb1X2 = Number of BetBrain bookmakers used to calculate match odds averages and maximums
    BbMxH = Betbrain maximum home win odds
    BbAvH = Betbrain average home win odds
    BbMxD = Betbrain maximum draw odds
    BbAvD = Betbrain average draw win odds
    BbMxA = Betbrain maximum away win odds
    BbAvA = Betbrain average away win odds

    MaxH = Oddsportal maximum home win odds
    MaxD = Oddsportal maximum draw win odds
    MaxA = Oddsportal maximum away win odds
    AvgH = Oddsportal average home win odds
    AvgD = Oddsportal average draw win odds
    AvgA = Oddsportal average away win odds



Key to total goals betting odds:

    BbOU = Number of BetBrain bookmakers used to calculate over/under 2.5 goals (total goals) averages and maximums
    BbMx>2.5 = Betbrain maximum over 2.5 goals
    BbAv>2.5 = Betbrain average over 2.5 goals
    BbMx<2.5 = Betbrain maximum under 2.5 goals
    BbAv<2.5 = Betbrain average under 2.5 goals

    GB>2.5 = Gamebookers over 2.5 goals
    GB<2.5 = Gamebookers under 2.5 goals
    B365>2.5 = Bet365 over 2.5 goals
    B365<2.5 = Bet365 under 2.5 goals


Key to Asian handicap betting odds:

    BbAH = Number of BetBrain bookmakers used to Asian handicap averages and maximums
    BbAHh = Betbrain size of handicap (home team)
    BbMxAHH = Betbrain maximum Asian handicap home team odds
    BbAvAHH = Betbrain average Asian handicap home team odds
    BbMxAHA = Betbrain maximum Asian handicap away team odds
    BbAvAHA = Betbrain average Asian handicap away team odds

    GBAHH = Gamebookers Asian handicap home team odds
    GBAHA = Gamebookers Asian handicap away team odds
    GBAH = Gamebookers size of handicap (home team)
    LBAHH = Ladbrokes Asian handicap home team odds
    LBAHA = Ladbrokes Asian handicap away team odds
    LBAH = Ladbrokes size of handicap (home team)
    B365AHH = Bet365 Asian handicap home team odds
    B365AHA = Bet365 Asian handicap away team odds
    B365AH = Bet365 size of handicap (home team)


Closing odds (last odds before match starts)

    PSCH = Pinnacle closing home win odds
    PSCD = Pinnacle closing draw odds
    PSCA = Pinnacle closing away win odds

Football-Data would like to acknowledge the following sources which have been utilised in the compilation of Football-Data's results and odds files.


Current results (full time, half time)
Xcores - http://www.xcores .com

Match statistics
Sportinglife, ESPN Soccer, Bundesliga.de, Gazzetta.it and Football.fr

    Bookmakers betting odds
    Betbrain - http://www.betbrain.com
    Oddsportal - http://www.oddsportal.com
    Individual bookmakers

Betting odds for weekend games are collected Friday afternoons, and on Tuesday afternoons for midweek games.

Additional match statistics (corners, shots, bookings, referee etc.) for the 2000/01 and 2001/02 seasons for the English, Scottish and German leagues were provided by Sports.com (now under new ownership and no longer available).

[Teams Attribute](https://sofifa.com/teams/hot)

In [10]:
# 用这个框对你计划使用的所有数据包进行设置
#   导入语句。
import pandas as pd
from zipfile import ZipFile
import matplotlib.pyplot as plt
import sqlite3
%matplotlib inline
# 务必包含一个‘magic word’（带有“%”的***），以便将你的视图
#   与 notebook 保持一致。关于更多信息，请访问该网页：
#   http://ipython.readthedocs.io/en/stable/interactive/magics.html

In [12]:
with ZipFile("./database.sqlite.zip", "r") as zfile:
    # connect to database
    zfile.extract("database.sqlite")
    conn = sqlite3.connect("database.sqlite")

In [15]:
df_match = pd.read_sql("SELECT * FROM Match", conn)
df_attribute = pd.read_sql("SELECT * FROM Team_Attributes", conn)

In [14]:
df_match.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [16]:
df_attribute.head()

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

In [32]:
df_match.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Data columns (total 115 columns):
id                  int64
country_id          int64
league_id           int64
season              object
stage               int64
date                object
match_api_id        int64
home_team_api_id    int64
away_team_api_id    int64
home_team_goal      int64
away_team_goal      int64
home_player_X1      float64
home_player_X2      float64
home_player_X3      float64
home_player_X4      float64
home_player_X5      float64
home_player_X6      float64
home_player_X7      float64
home_player_X8      float64
home_player_X9      float64
home_player_X10     float64
home_player_X11     float64
away_player_X1      float64
away_player_X2      float64
away_player_X3      float64
away_player_X4      float64
away_player_X5      float64
away_player_X6      float64
away_player_X7      float64
away_player_X8      float64
away_player_X9      float64
away_player_X10     float64
away_player_X11     float64
home_player_Y1      float64
home_player_Y2      float64
home_player_Y3      float64
home_player_Y4      float64
home_player_Y5      float64
home_player_Y6      float64
home_player_Y7      float64
home_player_Y8      float64
home_player_Y9      float64
home_player_Y10     float64
home_player_Y11     float64
away_player_Y1      float64
away_player_Y2      float64
away_player_Y3      float64
away_player_Y4      float64
away_player_Y5      float64
away_player_Y6      float64
away_player_Y7      float64
away_player_Y8      float64
away_player_Y9      float64
away_player_Y10     float64
away_player_Y11     float64
home_player_1       float64
home_player_2       float64
home_player_3       float64
home_player_4       float64
home_player_5       float64
home_player_6       float64
home_player_7       float64
home_player_8       float64
home_player_9       float64
home_player_10      float64
home_player_11      float64
away_player_1       float64
away_player_2       float64
away_player_3       float64
away_player_4       float64
away_player_5       float64
away_player_6       float64
away_player_7       float64
away_player_8       float64
away_player_9       float64
away_player_10      float64
away_player_11      float64
goal                object
shoton              object
shotoff             object
foulcommit          object
card                object
cross               object
corner              object
possession          object
B365H               float64
B365D               float64
B365A               float64
BWH                 float64
BWD                 float64
BWA                 float64
IWH                 float64
IWD                 float64
IWA                 float64
LBH                 float64
LBD                 float64
LBA                 float64
PSH                 float64
PSD                 float64
PSA                 float64
WHH                 float64
WHD                 float64
WHA                 float64
SJH                 float64
SJD                 float64
SJA                 float64
VCH                 float64
VCD                 float64
VCA                 float64
GBH                 float64
GBD                 float64
GBA                 float64
BSH                 float64
BSD                 float64
BSA                 float64
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB

In [33]:
df_attribute.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 25 columns):
id                                1458 non-null int64
team_fifa_api_id                  1458 non-null int64
team_api_id                       1458 non-null int64
date                              1458 non-null object
buildUpPlaySpeed                  1458 non-null int64
buildUpPlaySpeedClass             1458 non-null object
buildUpPlayDribbling              489 non-null float64
buildUpPlayDribblingClass         1458 non-null object
buildUpPlayPassing                1458 non-null int64
buildUpPlayPassingClass           1458 non-null object
buildUpPlayPositioningClass       1458 non-null object
chanceCreationPassing             1458 non-null int64
chanceCreationPassingClass        1458 non-null object
chanceCreationCrossing            1458 non-null int64
chanceCreationCrossingClass       1458 non-null object
chanceCreationShooting            1458 non-null int64
chanceCreationShootingClass       1458 non-null object
chanceCreationPositioningClass    1458 non-null object
defencePressure                   1458 non-null int64
defencePressureClass              1458 non-null object
defenceAggression                 1458 non-null int64
defenceAggressionClass            1458 non-null object
defenceTeamWidth                  1458 non-null int64
defenceTeamWidthClass             1458 non-null object
defenceDefenderLineClass          1458 non-null object
dtypes: float64(1), int64(11), object(13)
memory usage: 284.8+ KB

In [34]:
df_attribute.select_dtypes("object").head()

,date,buildUpPlaySpeedClass,buildUpPlayDribblingClass,buildUpPlayPassingClass,buildUpPlayPositioningClass,chanceCreationPassingClass,chanceCreationCrossingClass,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressureClass,defenceAggressionClass,defenceTeamWidthClass,defenceDefenderLineClass
0,2010-02-22 00:00:00,Balanced,Little,Mixed,Organised,Normal,Normal,Normal,Organised,Medium,Press,Normal,Cover
1,2014-09-19 00:00:00,Balanced,Normal,Mixed,Organised,Normal,Normal,Normal,Organised,Medium,Press,Normal,Cover
2,2015-09-10 00:00:00,Balanced,Normal,Mixed,Organised,Normal,Normal,Normal,Organised,Medium,Press,Normal,Cover
3,2010-02-22 00:00:00,Fast,Little,Long,Organised,Risky,Lots,Lots,Organised,Medium,Double,Wide,Cover
4,2011-02-22 00:00:00,Balanced,Little,Mixed,Organised,Normal,Normal,Normal,Organised,Medium,Press,Normal,Cover

<a id='wrangling'></a>
## 数据整理

> **提示**：在报告的这一部分中载入数据，检查简洁度，然后整理和清理数据集，以便进行分析。请务必将步骤仔细归档，并确定清理决策是否正确。

### 常规属性

In [ ]:
# 加载数据并打印几行。进行这几项操作，来检查数据
#   类型，以及是否有缺失数据或错误数据的情况。

> **提示**：_不应_在每个 notebook 框 (cell) 中进行太多操作。可以自由创建框，来进行数据探索。在这个项目中，可以在初始 notebook 中进行大量探索性操作。不要求对其进行组织，但请务必仔细阅读备注，理解每个代码框的用途。完成分析之后，你可以创建 notebook 副本，在其中去除多余数据，组织好你的每一步分析，从而形成信息连贯、结构紧密的报告。

> **提示**：请务必向你的读者告知你在调查中采取的步骤。在每个代码框或每组相关代码框后面，用 markdown 框对前面的框中的调查结果向读者进行说明。你需要尽量做到这一点，以便读者更好地理解后续框中的内容。

### 数据清理（请用更具体的标题来代替该标题。）

In [ ]:
# 在讨论数据结构和需要解决的任何问题之后，
#   在本部分的第二小部分进行这些清理步骤。

<a id='eda'></a>
## 探索性数据分析

> **提示**在你完成数据整理和清理之后，现在可以进行探索性数据分析了。你需要计算统计值，创建可视化图表，解决你在一开始的简介部分中提出的研究问题。我们推荐你采用系统化方法。一次只探索一个变量，然后探索变量之间的关系。

### 研究问题 1（请替换这一标题名称。 ）

In [ ]:
# 用这个代码框和其它代码框探索数据。请务必记得添加
#   Markdown 框，以便记录你的观察和调查结果。

### 研究问题 2（请替换这一标题名称。）

In [ ]:
# 请继续探索数据，解决你额外的研究问题。
#   如果有其它问题要调查，
#   请根据需要添加更多标题。

<a id='conclusions'></a>
## 结论

> **提示**：最后，你需要总结自己的调查结果。请确保你了解在探索过程中的局限性。如果尚未进行任何统计检验，不要做出任何统计结论。切记不要根据相关关系贸然推导出因果关系！

> **提示**：如果你对自己的研究成果感到满意，应将其副本保存为 HTML 或 PDF 形式。在导出报告之前请检查一遍，确保报告结构完整，信息连贯。应删除所有类似的“提示”引用段，以保持报告中的简洁度。在提交之前，你还需要查看在课程结尾的项目提交页面中的项目审阅规范。

> 如需将报告导出到工作区，你可以运行下面的代码框。如果正确，会返回代码 0，工作区目录下会生成 .html 文件（单击左上角的 jupyter 图标）。也可以通过 **文件** > **下载为** 子菜单下载 html 报告，然后手动上传到工作区目录。完成之后，可以单击右下角的“提交项目”，来提交你的项目。恭喜你！

In [ ]:
from subprocess import call
call(['python', '-m', 'nbconvert', 'Investigate_a_Dataset.ipynb'])